import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Investment, AggregatedData } from '../types';
import { formatCurrency } from '../utils/helpers';

import { askGemini } from './aiService';

interface ReportData {
    investments: Investment[];
    stats: any;
    allocationData: AggregatedData[];
    userName?: string;
    aiAnalysis?: string; // New field
}

export const generateAIAnalysis = async (data: ReportData): Promise<string> => {
    const prompt = `
    Act as a professional Wealth Manager for a High Net Worth Individual. 
    Analyze the following portfolio snapshot and write a concise, professional "Monthly Performance Commentary" (approx 150 words).
    
    Data:
    - Total Net Worth: ${formatCurrency(data.stats.totalCurrent)}
    - Total P/L: ${data.stats.totalPL >= 0 ? '+' : ''}${formatCurrency(data.stats.totalPL)} (${data.stats.totalPLPercent}%)
    - Top Holding: ${data.investments.sort((a, b) => b.currentValue - a.currentValue)[0]?.name || 'N/A'}
    - Asset Allocation: ${data.allocationData.map(d => `${d.name}: ${Math.round((d.value / data.stats.totalAssets) * 100)}%`).join(', ')}

    Structure your response in markdown (bolding key figures):
    1. **Executive Summary**: Overall health and major moves.
    2. **Risk & Opportunity**: One key risk (e.g. concentration) and one opportunity.
    3. **Outlook**: A generic but professional forward-looking sentence based on general market principles (do not hallucinate specific future news).
    
    Tone: Professional, Objective, Insightful. No financial advice disclaimers needed in the text itself.
    `;

    return await askGemini(prompt, true); // Use Pro for better writing
};

export const generateMonthlyReport = async (data: ReportData) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

    // --- Helper Colors ---
    const BRAND_COLOR: [number, number, number] = [79, 70, 229]; // Indigo-600
    const ACCENT_COLOR: [number, number, number] = [16, 185, 129]; // Emerald 500
    const TEXT_COLOR: [number, number, number] = [30, 41, 59]; // Slate 800
    const SUBTEXT_COLOR: [number, number, number] = [100, 116, 139]; // Slate 500
    const BG_LIGHT: [number, number, number] = [248, 250, 252]; // Slate 50

    // --- Header Strip ---
    doc.setFillColor(...BRAND_COLOR);
    doc.rect(0, 0, pageWidth, 4, 'F');

    // --- Title Section ---
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(24);
    doc.setTextColor(...TEXT_COLOR);
    doc.text('WEALTH AGGREGATOR', 14, 25);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...SUBTEXT_COLOR);
    doc.text('MONTHLY PERFORMANCE REPORT', 14, 32);

    doc.setFontSize(10);
    doc.setTextColor(...TEXT_COLOR);
    doc.text(today, pageWidth - 14, 25, { align: 'right' });
    doc.setTextColor(...SUBTEXT_COLOR);
    doc.text('Generated by Wealth Pro', pageWidth - 14, 32, { align: 'right' });

    doc.setDrawColor(226, 232, 240); // Slate 200
    doc.setLineWidth(0.5);
    doc.line(14, 40, pageWidth - 14, 40);

    // --- Executive Summary (Cards) ---
    const startY = 55;

    // Helper to draw card
    const drawCard = (x: number, title: string, value: string, subtext?: string, isPositive?: boolean) => {
        doc.setFillColor(...BG_LIGHT);
        doc.roundedRect(x, startY, 55, 30, 2, 2, 'F');

        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...SUBTEXT_COLOR);
        doc.text(title.toUpperCase(), x + 5, startY + 10);

        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        if (isPositive === undefined) doc.setTextColor(...TEXT_COLOR);
        else {
            const c: [number, number, number] = isPositive ? [16, 185, 129] : [220, 38, 38];
            doc.setTextColor(...c);
        }

        doc.text(value, x + 5, startY + 22);

        if (subtext) {
            doc.setFontSize(8);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(...SUBTEXT_COLOR);
            doc.text(subtext, x + 55 - 5, startY + 22, { align: 'right' });
        }
    };

    drawCard(14, 'Net Worth', formatCurrency(data.stats.totalCurrent || 0));
    drawCard(74, 'Invested Capital', formatCurrency(data.stats.totalInvested || 0));
    drawCard(134, 'Total P/L',
        (data.stats.totalPL >= 0 ? '+' : '') + formatCurrency(data.stats.totalPL || 0),
        (data.stats.totalPLPercent || '0') + '%',
        data.stats.totalPL >= 0
    );

    // --- Asset Allocation Section ---
    let yPos = startY + 45;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...TEXT_COLOR);
    doc.text('Asset Allocation', 14, yPos);

    const allocationTableData = data.allocationData.map(d => [
        d.name,
        formatCurrency(d.value),
        ((d.value / data.stats.totalAssets) * 100).toFixed(1) + '%'
    ]);

    // @ts-ignore
    autoTable(doc, {
        startY: yPos + 5,
        head: [['Asset Class', 'Value', 'Allocation']],
        body: allocationTableData,
        headStyles: {
            fillColor: BRAND_COLOR,
            fontSize: 9,
            fontStyle: 'bold',
            halign: 'left'
        },
        bodyStyles: {
            fontSize: 9,
            textColor: TEXT_COLOR
        },
        alternateRowStyles: {
            fillColor: BG_LIGHT
        },
        theme: 'plain',
        tableLineColor: [226, 232, 240],
        tableLineWidth: 0.1,
    });

    // --- Top Holdings Section ---
    // @ts-ignore
    yPos = doc.lastAutoTable.finalY + 20;

    // Check page break
    if (yPos > pageHeight - 60) {
        doc.addPage();
        yPos = 30;
    }

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Top Performers', 14, yPos);

    const holdingsData = data.investments
        .sort((a, b) => b.currentValue - a.currentValue)
        .slice(0, 8) // Top 8
        .map(inv => {
            const ret = ((inv.currentValue - inv.investedAmount) / inv.investedAmount * 100);
            return [
                inv.name,
                inv.type,
                formatCurrency(inv.investedAmount),
                formatCurrency(inv.currentValue),
                { content: (ret >= 0 ? '+' : '') + ret.toFixed(1) + '%', styles: { textColor: ret >= 0 ? [16, 185, 129] : [220, 38, 38], fontStyle: 'bold' } }
            ];
        });

    // @ts-ignore
    autoTable(doc, {
        startY: yPos + 5,
        head: [['Asset', 'Type', 'Invested', 'Current', 'Return']],
        body: holdingsData as any,
        headStyles: {
            fillColor: [51, 65, 85], // Slate 700
            fontSize: 9,
        },
        bodyStyles: {
            fontSize: 9
        },
        theme: 'striped'
    });

    // --- Market Commentary (AI) ---
    if (data.aiAnalysis) {
        yPos += 15;

        // Background box for AI Analysis
        doc.setFillColor(240, 253, 244); // Green-50ish (Emerald-50) or Slate-50? Let's go Slate-50
        doc.setFillColor(...BG_LIGHT);
        doc.roundedRect(14, yPos, pageWidth - 28, 60, 2, 2, 'F');

        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...BRAND_COLOR);
        doc.text('Performance Commentary (AI Generated)', 19, yPos + 10);

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...TEXT_COLOR);

        // Split text to fit
        const splitText = doc.splitTextToSize(data.aiAnalysis.replace(/\*\*/g, ''), pageWidth - 38); // Remove markdown bolding for PDF text
        doc.text(splitText, 19, yPos + 20);

        yPos += 70; // Move down past the box
    }


    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(...SUBTEXT_COLOR);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageHeight - 10, { align: 'right' });
        doc.text('Generated by Wealth Aggregator V1.1', 14, pageHeight - 10);
    }

    // Save
    doc.save(`WealthReport_${new Date().toISOString().slice(0, 10)}.pdf`);
};


